select PRODUCT.PRODUCT_CODE, sum(PRODUCT.PRICE*OFFLINE_SALE.SALES_AMOUNT) as SALES
from OFFLINE_SALE
join PRODUCT
on OFFLINE_SALE.PRODUCT_ID = PRODUCT.PRODUCT_ID
group by PRODUCT.PRODUCT_CODE
order by SALES desc, PRODUCT.PRODUCT_CODE asc;