-- CAR_RENTAL_COMPANY_CAR: 회사에서 대여 중인 자동차들의 정보
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: 자동차 대여 기록 정보
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN: 자동차 종류 별 대여 기간 종류 별 할인 정책 정보
-- 조건1: 자동차 종류가 '세단' 또는 'SUV' 인 자동차
-- 조건2: 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 조건3: 30일간의 대여 금액이 50만원 이상 200만원 미만

SELECT C.CAR_ID, C.CAR_TYPE, ROUND(C.DAILY_FEE*30*((100-P.DISCOUNT_RATE)/100), 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON (C.CAR_TYPE = P.CAR_TYPE)
WHERE CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
) AND C.CAR_TYPE IN ('세단', 'SUV') AND P.DURATION_TYPE = '30일 이상'
AND (C.DAILY_FEE*30*((100-P.DISCOUNT_RATE)/100) >= 500000 AND C.DAILY_FEE*30*((100-P.DISCOUNT_RATE)/100) < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;

