-- CAR_RENTAL_COMPANY_CAR: 대여 중인 자동차들의 정보
-- CAR_RENTAL_COMPANY_RENTAL_HISTORY: 자동차 대여 기록 정보
-- CAR_RENTAL_COMPANY_DISCOUNT_PLAN: 자동차 종류 별 대여 기간 종류 별 할인 정책 정보

-- 조건1: 자동차 종류가 '세단' 또는 'SUV'
-- 조건2: 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능
-- 조건3: 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차

SELECT CAR_ID, A.CAR_TYPE, DAILY_FEE*30*((100-DISCOUNT_RATE)/100) AS FEE
FROM (
    SELECT CAR_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE DURATION_TYPE = '30일 이상'
) A
JOIN (
    SELECT CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
    )
) B ON (A.CAR_TYPE = B.CAR_TYPE)
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;


