-- ECOLI_DATA: 실험실에서 배양한 대장균들의 정보
SELECT ID, 
    CASE NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC)
        WHEN 1 THEN 'CRITICAL'
        WHEN 2 THEN 'HIGH'
        WHEN 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS P
FROM ECOLI_DATA
ORDER BY ID;