-- REST_INFO: 식당의 정보
-- REST_REVIEW: 식당의 리뷰 정보
-- 조건1: 서울에 위치한 식당들
-- 조건2: 리뷰 평균 점수 -> 소수점 세 번째 자리에서 반올림
SELECT R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS,
    ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW R
LEFT JOIN (
    SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS
    FROM REST_INFO
    WHERE ADDRESS LIKE '서울%'
) I ON (R.REST_ID = I.REST_ID)
WHERE I.REST_ID IS NOT NULL
GROUP BY R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS
ORDER BY SCORE DESC, I.FAVORITES DESC;