-- USED_GOODS_BOARD: 중고 거래 게시판 정보
-- USED_GOODS_USER: 중고 거래 게시판 사용자 정보
select B.WRITER_ID AS USER_ID, U.NICKNAME AS NICKNAME, SUM(B.PRICE) AS TOTAL_SALES
from USED_GOODS_BOARD B
join USED_GOODS_USER U
on (B.WRITER_ID = U.USER_ID)
where STATUS = 'DONE'
group by B.WRITER_ID
having SUM(B.PRICE) >= 700000
order by SUM(B.PRICE);