-- CAR_RENTAL_COMPANY_RENTAL_HISTORY
select MONTH(H.START_DATE) AS MONTH, H.CAR_ID AS CAR_ID, COUNT(*) AS RECORDS
from CAR_RENTAL_COMPANY_RENTAL_HISTORY H
left join (
    select CAR_ID, START_DATE, COUNT(*)
    from CAR_RENTAL_COMPANY_RENTAL_HISTORY
    where DATE_FORMAT(START_DATE, '%Y-%m') >= '2022-08'
    and DATE_FORMAT(START_DATE, '%Y-%m') <= '2022-10'
    group by CAR_ID
    having COUNT(*) >= 5
) SUB
on (H.CAR_ID = SUB.CAR_ID)
where SUB.CAR_ID IS NOT NULL and DATE_FORMAT(H.START_DATE, '%Y-%m') >= '2022-08'
    and DATE_FORMAT(H.START_DATE, '%Y-%m') <= '2022-10'
group by H.CAR_ID, MONTH(H.START_DATE)
order by MONTH, CAR_ID desc;

