-- FISH_INFO: 잡은 물고기들의 정보
-- FISH_NAME_INFO: 물고기의 이름에 대한 정보
SELECT ID, FISH_NAME, LENGTH
FROM (
    SELECT ID, FISH_NAME, LENGTH, ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS RN
    FROM FISH_INFO 
    JOIN FISH_NAME_INFO USING (FISH_TYPE)
) SUB
WHERE RN = 1
ORDER BY ID;

