-- 코드를 작성해주세요
SELECT A.SCORE SCORE, EMP_NO, B.EMP_NAME EMP_NAME, B.POSITION POSITION, B.EMAIL EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
) A
JOIN HR_EMPLOYEES B USING (EMP_NO)
ORDER BY SCORE DESC
LIMIT 1;

