-- FIRST_HALF: 아이스크림 가게의 상반기 주문 정보
-- ICECREAM_INFO: 아이스크림 성분에 대한 정보
select INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
from FIRST_HALF F
join ICECREAM_INFO I
on (F.FLAVOR = I.FLAVOR)
group by INGREDIENT_TYPE
order by TOTAL_ORDER;