SELECT SUB.CATEGORY, SUB.PRICE AS MAX_PRICE, SUB.PRODUCT_NAME
FROM (
    SELECT CATEGORY, ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RN, PRICE, PRODUCT_NAME
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
) SUB
WHERE RN = 1
ORDER BY MAX_PRICE DESC;